=== pklaus/docker-phoebus-archiver/app/engineconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the ArchiveEngine Configuration         -->
<!-- Note that we do not allow empty configurations: -->
<!-- Each config. must contain at least one group,   -->
<!-- and each group must contain at least 1 channel. -->
<!ELEMENT engineconfig ((write_period|get_threshold|
                         file_size|ignored_future|
                         buffer_reserve|
                         max_repeat_count|disconnect)*,
                         group*)>
<!ELEMENT group (name,channel*)>
<!ELEMENT channel (name,period,(scan|monitor),disable?)>
<!ELEMENT write_period (#PCDATA)><!-- int seconds -->
<!ELEMENT get_threshold (#PCDATA)><!-- int seconds -->
<!ELEMENT file_size (#PCDATA)><!-- MB -->
<!ELEMENT ignored_future (#PCDATA)><!-- double hours -->
<!ELEMENT buffer_reserve (#PCDATA)><!-- int times -->
<!ELEMENT max_repeat_count (#PCDATA)><!-- int times -->
<!ELEMENT disconnect EMPTY>
<!ELEMENT name (#PCDATA)>
<!ELEMENT period (#PCDATA)><!-- double seconds -->
<!ELEMENT scan EMPTY>
<!ELEMENT monitor EMPTY>
<!ELEMENT disable EMPTY>

=== pklaus/docker-phoebus-archiver/compose-example/Example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE engineconfig SYSTEM "./engineconfig.dtd">
<engineconfig>
  <group>
    <name>Example Group 1</name>
      <channel><name>scs:circle:tick</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:circle:angle</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:line:a</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:circle:x</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:circle:y</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calcExample</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calcExample1</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calc1</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calcExample2</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calc2</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calcExample3</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:calc3</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:line:b</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:aiExample</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:aiExample1</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:ai1</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:aiExample2</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:ai2</name>		<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:aiExample3</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:ai3</name>		<period>00:00:01</period><monitor/></channel>
  </group>
  <group>
    <name>Example Group 2</name>
      <channel><name>scs:xxxExample     </name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:compressExample</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:EXAMPLE:version</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:aSubExample</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:subExample</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:circle:step</name>	<period>00:00:01</period><monitor/></channel>
      <channel><name>scs:circle:period</name>	<period>00:00:01</period><monitor/></channel>
  </group>
</engineconfig>
